### PR TITLE
German sentences

### PR DESCRIPTION
**Pull request by manu183**
Added German sentences for issue #1

### CODE REVIEW

**Comment by the-ethan-hunt** [comment]
Nice PR @manu183 . But would you also include some nice vocabulary that includes food items? See `CONTRIBUTING.md` for more. :smile:

**Comment by manu183** [comment]
Thank you for the feedback @the-ethan-hunt. I've been quite busy the last days, gonna add some more vocabulary over the weekend :)

**Comment by manu183** [comment]
I've added some more vocab, @the-ethan-hunt :)

**Comment by the-ethan-hunt** [comment]
Great @manu183 ! Can you create more phrasebooks for German language?

**Pull request merged**
